Answer.create(content: "The world is blue because it's inside the eye of a giant.", user_id: 1, question_id: 1)
Answer.create(content: "Oh my god that would be amazing. But deeply disturbing as well. Although this is highly unlikely as the reason for King Aery's madness. The Targeryans have a history of insanity due to many generations of inbreeding. In fact there's an old saying. Every time a Targeryan is born, the gods flip a coin to determine if they are mad.", user_id: 2, question_id: 2)
Answer.create(content: "49", user_id: 3, question_id: 3)
Answer.create(content: "No. Call animal services immediately.", user_id: 4, question_id: 4)
Answer.create(content: "Set up a motion sensor activated camera that turns on automatically when it detects motion in the kitchen.", user_id: 5, question_id: 5)
Answer.create(content: "Probably.", user_id: 6, question_id: 6)
Answer.create(content: "My guess is that the homeless person doesn't really care. He/she was probably just trying to get your atention.", user_id: 7, question_id: 7)
Answer.create(content: "Extraordinarily. People like to think that as CEO, you get to just order everyone around and that people will do everything for you. WRONG. Before I sold my company, Aviato, I was working round the clock to keep us from burning through too much cash.", user_id: 8, question_id: 8)
Answer.create(content: "Because he's getting dragged down to hell.", user_id: 9, question_id: 9)
Answer.create(content: "Personally, I think Australians and Trinidadians have the sexiest accents.", user_id: 10, question_id: 10)